# Final Project - Twitter Sentiment Analysis

In [1]:
import pandas as pd

In [11]:
twit = pd.read_csv("training.1600000.processed.noemoticon.csv", header=None, encoding='latin1')

headers = ['target', 'id', 'date', 'flag', 'user', 'text']
twit.columns = headers

twit.head()

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [12]:
twit.shape

(1600000, 6)

In [13]:
twit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   target  1600000 non-null  int64
 1   id      1600000 non-null  int64
 2   date    1600000 non-null  object
 3   flag    1600000 non-null  object
 4   user    1600000 non-null  object
 5   text    1600000 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

In [14]:
twit.head(50)

,target,id,date,flag,user,text
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
5,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew
6,0,1467811592,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,mybirch,Need a hug
7,0,1467811594,Mon Apr 06 22:20:03 PDT 2009,NO_QUERY,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...
8,0,1467811795,Mon Apr 06 22:20:05 PDT 2009,NO_QUERY,2Hood4Hollywood,@Tatiana_K nope they didn't have it
9,0,1467812025,Mon Apr 06 22:20:09 PDT 2009,NO_QUERY,mimismo,@twittera que me muera ?
10,0,1467812416,Mon Apr 06 22:20:16 PDT 2009,NO_QUERY,erinx3leannexo,spring break in plain city... it's snowing
11,0,1467812579,Mon Apr 06 22:20:17 PDT 2009,NO_QUERY,pardonlauren,I just re-pierced my ears
12,0,1467812723,Mon Apr 06 22:20:19 PDT 2009,NO_QUERY,TLeC,@caregiving I couldn't bear to watch it. And ...
13,0,1467812771,Mon Apr 06 22:20:19 PDT 2009,NO_QUERY,robrobbierobert,"@octolinz16 It it counts, idk why I did either..."
14,0,1467812784,Mon Apr 06 22:20:20 PDT 2009,NO_QUERY,bayofwolves,"@smarrison i would've been the first, but i di..."
15,0,1467812799,Mon Apr 06 22:20:20 PDT 2009,NO_QUERY,HairByJess,@iamjazzyfizzle I wish I got to watch it with ...
16,0,1467812964,Mon Apr 06 22:20:22 PDT 2009,NO_QUERY,lovesongwriter,Hollis' death scene will hurt me severely to w...
17,0,1467813137,Mon Apr 06 22:20:25 PDT 2009,NO_QUERY,armotley,about to file taxes
18,0,1467813579,Mon Apr 06 22:20:31 PDT 2009,NO_QUERY,starkissed,@LettyA ahh ive always wanted to see rent lov...
19,0,1467813782,Mon Apr 06 22:20:34 PDT 2009,NO_QUERY,gi_gi_bee,@FakerPattyPattz Oh dear. Were you drinking ou...
20,0,1467813985,Mon Apr 06 22:20:37 PDT 2009,NO_QUERY,quanvu,@alydesigns i was out most of the day so didn'...
21,0,1467813992,Mon Apr 06 22:20:38 PDT 2009,NO_QUERY,swinspeedx,"one of my friend called me, and asked to meet ..."
22,0,1467814119,Mon Apr 06 22:20:40 PDT 2009,NO_QUERY,cooliodoc,@angry_barista I baked you a cake but I ated it
23,0,1467814180,Mon Apr 06 22:20:40 PDT 2009,NO_QUERY,viJILLante,this week is not going as i had hoped
24,0,1467814192,Mon Apr 06 22:20:41 PDT 2009,NO_QUERY,Ljelli3166,blagh class at 8 tomorrow
25,0,1467814438,Mon Apr 06 22:20:44 PDT 2009,NO_QUERY,ChicagoCubbie,I hate when I have to call and wake people up
26,0,1467814783,Mon Apr 06 22:20:50 PDT 2009,NO_QUERY,KatieAngell,Just going to cry myself to sleep after watchi...
27,0,1467814883,Mon Apr 06 22:20:52 PDT 2009,NO_QUERY,gagoo,im sad now Miss.Lilly
28,0,1467815199,Mon Apr 06 22:20:56 PDT 2009,NO_QUERY,abel209,ooooh.... LOL that leslie.... and ok I won't ...
29,0,1467815753,Mon Apr 06 22:21:04 PDT 2009,NO_QUERY,BaptisteTheFool,Meh... Almost Lover is the exception... this t...
30,0,1467815923,Mon Apr 06 22:21:07 PDT 2009,NO_QUERY,fatkat309,some1 hacked my account on aim now i have to ...
31,0,1467815924,Mon Apr 06 22:21:07 PDT 2009,NO_QUERY,EmCDL,@alielayus I want to go to promote GEAR AND GR...
32,0,1467815988,Mon Apr 06 22:21:09 PDT 2009,NO_QUERY,merisssa,thought sleeping in was an option tomorrow but...
33,0,1467816149,Mon Apr 06 22:21:11 PDT 2009,NO_QUERY,Pbearfox,@julieebaby awe i love you too!!!! 1 am here ...
34,0,1467816665,Mon Apr 06 22:21:21 PDT 2009,NO_QUERY,jsoo,@HumpNinja I cry my asian eyes to sleep at night
35,0,1467816749,Mon Apr 06 22:21:20 PDT 2009,NO_QUERY,scarletletterm,ok I'm sick and spent an hour sitting in the s...
36,0,1467817225,Mon Apr 06 22:21:27 PDT 2009,NO_QUERY,crosland_12,@cocomix04 ill tell ya the story later not a ...
37,0,1467817374,Mon Apr 06 22:21:30 PDT 2009,NO_QUERY,ajaxpro,@MissXu sorry! bed time came here (GMT+1) ht...
38,0,1467817502,Mon Apr 06 22:21:32 PDT 2009,NO_QUERY,Tmttq86,@fleurylis I don't either. Its depressing. I d...
39,0,1467818007,Mon Apr 06 22:21:39 PDT 2009,NO_QUERY,Anthony_Nguyen,Bed. Class 8-12. Work 12-3. Gym 3-5 or 6. Then...
40,0,1467818020,Mon Apr 06 22:21:39 PDT 2009,NO_QUERY,itsanimesh,really don't feel like getting up today... but...
41,0,1467818481,Mon Apr 06 22:21:46 PDT 2009,NO_QUERY,lionslamb,He's the reason for the teardrops on my guitar...
42,0,1467818603,Mon Apr 06 22:21:49 PDT 2009,NO_QUERY,kennypham,"Sad, sad, sad. I don't know why but I hate thi..."
43,0,1467818900,Mon Apr 06 22:21:53 PDT 2009,NO_QUERY,DdubsShellBell,@JonathanRKnight Awww I soo wish I was there t...
44,0,1467819022,Mon Apr 06 22:21:56 PDT 2009,NO_QUERY,hpfangirl94,Falling asleep. Just heard about that Tracy gi...
45,0,1467819650,Mon Apr 06 22:22:05 PDT 2009,NO_QUERY,antzpantz,@Viennah Yay! I'm happy for you with your job!...
46,0,1467819712,Mon Apr 06 22:22:06 PDT 2009,NO_QUERY,labrt2004,Just checked my user timeline on my blackberry...
47,0,1467819812,Mon Apr 06 22:22:07 PDT 2009,NO_QUERY,IrisJumbe,Oh man...was ironing @jeancjumbe's fave top to...
48,0,1467820206,Mon Apr 06 22:22:13 PDT 2009,NO_QUERY,peacoats,is strangely sad about LiLo and SamRo breaking...
49,0,1467820835,Mon Apr 06 22:22:25 PDT 2009,NO_QUERY,cyantist,@tea oh! i'm so sorry i didn't think about th...